integrations:
  rescuetime:
    frequency: "daily"
    overview: true
    top-categories: true
    top-activities: false
  google-fit:
    frequency: "daily"
    all: true
  # clockify:
  # spotify:
  # goodreads:
